# Generated by Django 3.0.5 on 2020-05-14 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('total', '0002_totaldate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TotalDate',
        ),
    ]
