# Generated by Django 3.0.5 on 2020-05-14 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0002_statedate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StateDate',
        ),
    ]
